const translations = {
  en: {skip:'Skip to content',explore:'Explore the workspace ↗',caption:'The real app, connected to a local demo server.',enlarge:'Click to enlarge ↗',native:'A familiar place for remote work.',featuresHeading:'Less switching.\nMore doing.',keyTag:'KEYCHAIN',close:'Close',features:'Features',privacy:'Privacy',eyebrow:'BUILT FOR YOUR MAC',headline:'Your servers.<br>One workspace.',intro:'Open a terminal. Move a file. Get back to work. SSH and SFTP together in a native Mac app.',pending:'Release in preparation',download:'Download for Mac',requirements:'Apple Silicon · macOS 14 or later · Free',terminalTitle:'A terminal for every server.',terminalBody:'Keep independent SSH sessions in tabs. Search your output, resize your terminal, and use your familiar command-line tools.',filesTitle:'Files, right beside your shell.',filesBody:'Browse remote folders and drag files between your Mac and your server. Follow progress in one transfer queue.',keysTitle:'Less typing. Your Keychain.',keysBody:'Organize connections into groups and reuse private keys. Choose which passwords and passphrases to remember in macOS Keychain.',privacyTitle:'Your connections stay on your Mac.',privacyBody:'No account, analytics, or terminal recording. Connections are stored locally. Passwords and private keys are stored in macOS Keychain when you choose to save them. The app connects directly to the servers you select.',privacyUpdates:'Optional update checks contact our public release host. This website and downloads are hosted on GitHub, whose infrastructure may keep standard access logs. Diagnostic files are shared only when you export and send them yourself.',release:'RELEASE NOTES',releaseTitle:'The first chapter.',releaseBody:'Version 0.1 brings saved connections, SSH terminals, a reusable key library, SFTP transfers, and Spanish and English interfaces.',releaseState:'A signed public download will appear here after release verification.',supportPending:'Support details available at launch',support:'Contact support'},
  es: {skip:'Ir al contenido',explore:'Conocé el espacio de trabajo ↗',caption:'La app real, conectada a un servidor local de demostración.',enlarge:'Clic para ampliar ↗',native:'Un lugar familiar para trabajar a distancia.',featuresHeading:'Menos cambios.\nMás trabajo hecho.',keyTag:'LLAVERO',close:'Cerrar',features:'Funciones',privacy:'Privacidad',eyebrow:'HECHO PARA TU MAC',headline:'Tus servidores.<br>Un solo espacio.',intro:'Abrí una terminal. Mové un archivo. Seguí trabajando. SSH y SFTP juntos en una app nativa para Mac.',pending:'Lanzamiento en preparación',download:'Descargar para Mac',requirements:'Apple Silicon · macOS 14 o posterior · Gratis',terminalTitle:'Una terminal para cada servidor.',terminalBody:'Mantené sesiones SSH independientes en pestañas. Buscá en la salida, ajustá la terminal y usá tus herramientas de siempre.',filesTitle:'Archivos, al lado de tu shell.',filesBody:'Explorá carpetas remotas y arrastrá archivos entre tu Mac y tu servidor. Seguí el progreso en una sola cola de transferencias.',keysTitle:'Menos escritura. Tu Llavero.',keysBody:'Organizá conexiones en grupos y reutilizá claves privadas. Elegí qué contraseñas y passphrases recordar en el Llavero de macOS.',privacyTitle:'Tus conexiones quedan en tu Mac.',privacyBody:'Sin cuenta, analítica ni grabación de terminal. Las conexiones se guardan localmente. Las contraseñas y claves privadas se guardan en el Llavero de macOS cuando lo elegís. La app se conecta directamente a los servidores que seleccionás.',privacyUpdates:'La búsqueda opcional de actualizaciones consulta nuestro alojamiento público de versiones. GitHub aloja esta web y las descargas, y su infraestructura puede conservar registros de acceso habituales. Los archivos de diagnóstico solo se comparten cuando vos los exportás y enviás.',release:'NOVEDADES',releaseTitle:'El primer capítulo.',releaseBody:'La versión 0.1 incorpora conexiones guardadas, terminales SSH, una biblioteca de claves, transferencias SFTP e interfaz en español e inglés.',releaseState:'La descarga pública firmada aparecerá aquí después de verificar el lanzamiento.',supportPending:'Los datos de soporte estarán disponibles en el lanzamiento',support:'Contactar a soporte'}
};
let language = navigator.language.startsWith('es') ? 'es' : 'en';
function render(){
 document.documentElement.lang=language;
 document.querySelector('nav').setAttribute('aria-label',language==='es'?'Navegación principal':'Main navigation');
 document.querySelectorAll('img[src="assets/app-workspace.png"]').forEach(img=>img.alt=language==='es'?'Termdex: conexión guardada, carpetas remotas y terminal SSH activa':'Termdex: saved connection, remote folders and an active SSH terminal');
 document.getElementById('expand').setAttribute('aria-label',language==='es'?'Ampliar captura de la aplicación':'Enlarge app screenshot');
 document.querySelectorAll('[data-i18n]').forEach(el=>{const value=translations[language][el.dataset.i18n];if(el.dataset.i18n==='headline')el.innerHTML=value;else el.textContent=value;});
 document.querySelectorAll('[data-app-name]').forEach(el=>el.textContent=window.SSHDESK_RELEASE.name);
 document.getElementById('language').textContent=language==='en'?'ES':'EN';
 document.getElementById('language').setAttribute('aria-label',language==='en'?'Cambiar a español':'Switch to English');
 const config=window.SSHDESK_RELEASE;
 if(config.downloadURL){const link=document.getElementById('download');link.href=config.downloadURL;link.removeAttribute('aria-disabled');link.textContent=translations[language].download;document.getElementById('releaseState').textContent='v'+config.version;}
 if(config.supportURL){const link=document.getElementById('support');link.href=config.supportURL;link.textContent=translations[language].support;}
 document.title=config.name+' — SSH & SFTP '+(language==='en'?'for Mac':'para Mac');
}
document.getElementById('language').addEventListener('click',()=>{language=language==='en'?'es':'en';render();});render();

const preview=document.getElementById('preview');
document.getElementById('expand').addEventListener('click',()=>preview.showModal());
preview.addEventListener('click',event=>{if(event.target===preview)preview.close();});
